# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

jobs:
- job:
  displayName: Windows
  pool:
    vmImage:
     windows-2019
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: ..
  - task: MSBuild@1
    inputs:
      solution: build/libmimalloc.sln
  - upload: $(Build.SourcesDirectory)/build
    artifact: windows

- job:
  displayName: Linux
  pool:
    vmImage:
     ubuntu-16.04
  strategy:
    matrix:
      Debug:
        CC: gcc
        BuildType: debug
        cmakeExtraArgs: -DCMAKE_BUILD_TYPE=Debug -DMI_CHECK_FULL=ON
      Release:
        CC: gcc
        BuildType: release
        cmakeExtraArgs: -DCMAKE_BUILD_TYPE=Debug

  steps:
  - task: CMake@1
    inputs:
      workingDirectory: $(BuildType)
      cmakeArgs: .. $(cmakeExtraArgs)

  - script: make -j$(nproc) -C $(BuildType)

  - script: make test -C $(BuildType)

  - upload: $(Build.SourcesDirectory)/$(BuildType)
    artifact: ubuntu-$(BuildType)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: '$(BuildType)/Testing/Temporary/LastTest.log'

- job:
  displayName: macOS
  pool:
    vmImage:
     macOS-10.14
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: ..
  - script: make -j$(sysctl -n hw.ncpu) -C build
  - upload: $(Build.SourcesDirectory)/build
    artifact: macos
